spring:
#Hibernate settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

#Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5433/firstDB
    username: postgres
    password: ${PGPASSWORD}

#Server settings
server:
  error:
    include-message: always

#Car properties
car:
  maxCar: 3
  isSortEnabledMap:
    id: "true"
    model: "false"
    mileage: "true"
    series: "false"